#!/usr/bin/env python3
"""Regenerate blog/posts.json and blog/posts-data.js from *-en.md and *-fa.md files."""

import json
import re
from pathlib import Path

BLOG_DIR = Path(__file__).resolve().parent
POSTS_DIR = BLOG_DIR / "posts"
OUTPUT_JSON = BLOG_DIR / "posts.json"
OUTPUT_JS = BLOG_DIR / "posts-data.js"

FRONTMATTER_RE = re.compile(r"^---\s*\r?\n(.*?)\r?\n---\s*\r?\n([\s\S]*)", re.DOTALL)
LOCALE_FILE_RE = re.compile(r"^(.+)-(en|fa)$")


def parse_frontmatter_block(block: str) -> dict:
    meta = {}
    for line in block.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        meta[key.strip()] = value
    return meta


def split_post(text: str) -> tuple[dict, str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    return parse_frontmatter_block(match.group(1)), match.group(2)


def locale_entry(meta: dict, locale: str, body: str) -> dict:
    direction = meta.get("dir", "rtl" if locale == "fa" else "ltr").lower()
    return {
        "title": meta.get("title", ""),
        "excerpt": meta.get("excerpt", ""),
        "dir": "rtl" if direction == "rtl" else "ltr",
        "lang": meta.get("lang", "fa" if locale == "fa" else "en"),
        "body": body,
    }


def main() -> None:
    grouped: dict[str, dict] = {}

    for path in sorted(POSTS_DIR.glob("*.md")):
        match = LOCALE_FILE_RE.match(path.stem)
        if not match:
            print(f"Skipping {path.name} (expected slug-en.md or slug-fa.md)")
            continue

        text = path.read_text(encoding="utf-8")
        if not text.strip():
            print(f"Skipping {path.name} (file is empty)")
            continue

        meta, body = split_post(text)
        if not meta.get("title"):
            print(f"Skipping {path.name} (missing title in front matter)")
            continue

        slug, locale = match.group(1), match.group(2)

        if slug not in grouped:
            grouped[slug] = {"slug": slug, "date": "", "locales": {}}

        entry = grouped[slug]
        if meta.get("date"):
            entry["date"] = meta["date"]
        entry["locales"][locale] = locale_entry(meta, locale, body)

    posts = list(grouped.values())
    posts.sort(key=lambda item: item["date"], reverse=True)

    index_posts = []
    for post in posts:
        index_post = {
            "slug": post["slug"],
            "date": post["date"],
            "locales": {
                locale: {k: v for k, v in data.items() if k != "body"}
                for locale, data in post["locales"].items()
            },
        }
        index_posts.append(index_post)

    json_text = json.dumps(index_posts, ensure_ascii=False, indent=2) + "\n"
    OUTPUT_JSON.write_text(json_text, encoding="utf-8")

    js_text = (
        "// Generated by build.sh — do not edit.\n"
        "window.BLOG_POSTS = "
        + json.dumps(posts, ensure_ascii=False, indent=2)
        + ";\n"
    )
    OUTPUT_JS.write_text(js_text, encoding="utf-8")

    print(f"Wrote {len(posts)} post(s) to {OUTPUT_JSON} and {OUTPUT_JS}")


if __name__ == "__main__":
    main()
